import { PostgresWebhookRepository } from '../repositories/postgres/postgres-repositories';
import { WebhookSubscriptionEntity } from '../domain/entities/entities';
import { AIServiceConnector, AIProposedAction, MerchantAIContext } from '../integrations/ai-connector/ai-service-connector';
import { WebhookEngine } from '../integrations/webhooks/webhook-engine';
import { logger } from '../monitoring/logger';
import crypto from 'crypto';

export class IntegrationService {
  private webhookRepo = new PostgresWebhookRepository();

  /**
   * Provides full merchant context to external AI models and agents.
   */
  public async getMerchantAIContext(merchantId: string): Promise<MerchantAIContext> {
    return AIServiceConnector.getMerchantContext(merchantId);
  }

  /**
   * Accepts actions and growth recommendations generated by the external AI team.
   */
  public async ingestAIAction(action: AIProposedAction) {
    return AIServiceConnector.ingestRecommendation(action);
  }

  /**
   * Registers a new generic webhook endpoint for external consumer teams.
   */
  public async registerWebhook(
    merchantId: string,
    targetUrl: string,
    subscribedEvents: string[]
  ): Promise<WebhookSubscriptionEntity> {
    const secret = crypto.randomBytes(32).toString('hex');

    const subscription = await this.webhookRepo.create({
      merchantId,
      targetUrl,
      secret,
      subscribedEvents,
      isActive: true,
      failureCount: 0,
    });

    logger.info({ subscriptionId: subscription.id, targetUrl }, 'Webhook subscription registered');
    return subscription;
  }

  /**
   * Triggers an outbound webhook dispatch with HMAC signing.
   */
  public async triggerWebhook(
    subscriptionId: string,
    event: string,
    data: any
  ): Promise<boolean> {
    const sub = await this.webhookRepo.findById(subscriptionId);
    if (!sub || !sub.isActive) return false;

    return WebhookEngine.dispatch(sub.id, sub.targetUrl, sub.secret, event, data);
  }
}
