import { AgentInfo } from '@/types';

export const PAYTM_COLORS = {
  navyDark: '#001740',
  navyDeep: '#002970',
  bluePrimary: '#005CE6',
  cyanBrand: '#00BAF2',
  cyanLight: '#E8F8FD',
  emeraldGlow: '#10B981',
  amberAlert: '#F59E0B',
  roseLeakage: '#F43F5E',
  darkBg: '#050B17',
  cardBg: 'rgba(11, 22, 44, 0.75)',
  glassBorder: 'rgba(0, 186, 242, 0.18)',
};

export const AGENT_REGISTRY: AgentInfo[] = [
  {
    id: 'bi',
    name: 'Business Intelligence Agent',
    role: 'Financial Diagnostics & Unit Economics',
    avatar: '📊',
    model: 'Groq GPT-OSS 120B',
    specialty: 'Margin breakdown, daily run rate, expense vs gross profit health',
    status: 'active',
    confidence: 98,
    lastAction: 'Analyzed ₹48,200 weekend run rate; Gross margin healthy at 19.4%',
  },
  {
    id: 'demand',
    name: 'Demand Forecast Agent',
    role: 'Predictive Sales & Seasonality',
    avatar: '📈',
    model: 'Prophet ML',
    specialty: 'Seasonal trends, festival spikes, rain/weather impacts, cricket matches',
    status: 'analyzing',
    confidence: 94,
    lastAction: 'Calculated +38% surge for snacks/dairy due to IND vs PAK IPL match',
  },
  {
    id: 'inventory',
    name: 'Inventory Agent',
    role: 'Autonomous Restocking & Stockout Prevention',
    avatar: '📦',
    model: 'XGBoost / LightGBM',
    specialty: 'Reorder safety thresholds, supplier lead-time buffers, dead stock alert',
    status: 'active',
    confidence: 96,
    lastAction: 'Drafted WhatsApp PO for 24 Amul Butter (500g) before Friday depletion',
  },
  {
    id: 'footfall',
    name: 'Footfall Agent',
    role: 'Customer Flow & Rush Hour Modeling',
    avatar: '🚶‍♂️',
    model: 'XGBoost / LightGBM',
    specialty: 'Hourly transaction density, heat maps, rainy evening shifts',
    status: 'active',
    confidence: 91,
    lastAction: 'Predicted peak rush between 6:30 PM - 8:45 PM (142 visits expected)',
  },
  {
    id: 'retention',
    name: 'Retention Agent',
    role: 'Customer Loyalty & Churn Prevention',
    avatar: '🔄',
    model: 'XGBoost / LightGBM',
    specialty: 'RFM customer scoring, dormant customer re-activation, khata trust index',
    status: 'active',
    confidence: 89,
    lastAction: 'Flagged 38 regular customers inactive for >10 days; drafted WhatsApp nudge',
  },
  {
    id: 'growth',
    name: 'Growth Agent',
    role: 'Strategic Expansion & Market Share',
    avatar: '🚀',
    model: 'Groq GPT-OSS 120B',
    specialty: 'High-margin cross-sell bundling, competitive basket defense vs Blinkit',
    status: 'active',
    confidence: 93,
    lastAction: 'Identified ₹3,200 daily upside by pairing evening tea premixes with rusks',
  },
  {
    id: 'campaign',
    name: 'Campaign Agent',
    role: 'Instant Flash Offers & Cashbacks',
    avatar: '🎯',
    model: 'Qwen Fast Multilingual',
    specialty: 'WhatsApp broadcast generator, Paytm UPI cashback rules, localized Hindi copy',
    status: 'idle',
    confidence: 95,
    lastAction: 'Generated 5% UPI cashback campaign for evening grocery baskets >₹350',
  },
  {
    id: 'execution',
    name: 'Execution Agent',
    role: 'Omnichannel Autopilot Action Engine',
    avatar: '⚡',
    model: 'Groq GPT-OSS 120B',
    specialty: 'Soundbox Hindi/English voice announcements, WhatsApp Business API, 1-tap PO',
    status: 'executing',
    confidence: 99,
    lastAction: 'Dispatched Soundbox voice morning briefing and supplier PO approval request',
  },
];
