apiVersion: v1
kind: Namespace
metadata:
  name: dukaanpay-prod
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dukaanpay-config
  namespace: dukaanpay-prod
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  AWS_REGION: "ap-south-1" # RBI sovereign compliance: Mumbai
  DB_HOST: "postgres-service.dukaanpay-prod.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "dukaanpay_db"
  KAFKA_BROKERS: "kafka-cluster-kafka-bootstrap.dukaanpay-prod.svc.cluster.local:9092"
  REDIS_HOST: "redis-master.dukaanpay-prod.svc.cluster.local"
  REDIS_PORT: "6379"
